import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClientProvider, ServerProvider } from 'src/providers/';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ServerProvider>
          <ClientProvider>
            <main className='flex min-h-screen min-w-screen flex-col items-center justify-center bg-gradient-to-br from-[#42A6FB] to-[#5A4DFD] text-white'>
              {children}
            </main>
          </ClientProvider>
        </ServerProvider>
      </body>
    </html>
  );
};

export default RootLayout;
